function [a,b,c,d,e,f] = loadheart(file)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/kevinryan/Documents/DataScienceMSc/MachineLearning/Coursework/heart.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/10/03 14:13:57

%% Initialize variables.
filename = file;
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
heart = table(dataArray{1:end-1}, 'VariableNames', {'age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','target'});
% Convert appropriate columns to categorical
heart.sex = categorical(heart.sex);
heart.cp = categorical(heart.cp);
heart.fbs = categorical(heart.fbs);
heart.restecg = categorical(heart.restecg);
heart.exang = categorical(heart.exang);
heart.slope = categorical(heart.slope);
heart.thal = categorical(heart.thal);
heart.target = categorical(heart.target);

% Generate male and female tables
heart_female = heart(heart.sex == '0',:);
heart_male = heart(heart.sex == '1',:);
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%% Code for this section adapted from https://davidlary.info/blog/2015/11/25/1760/
% Assign columns of table to input variables for Random Forest

In = heart(:,1:end-1); % Input table of features
In_female = heart_female(:,1:end-1);
In_male = heart_male(:,1:end-1);
Out = heart.target; % vector output of target values
Out_female = heart_female.target;
Out_male = heart_male.target;



a = In;
b = In_female;
c = In_male;
d = Out;
e = Out_female;
f = Out_male;
end